/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef _WSPROTO_H
#define _WSPROTO_H


class WinsockInterfaceClass;
extern WinsockInterfaceClass *PacketTransport;			//The object for interfacing with Winsock

#endif	//_WSPROTO_H
