/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef VQMALL_H
#define VQMALL_H

#include <vqm32/iff.h>
#include <vqm32/mono.h>
#include <vqm32/portio.h>
#include <vqm32/profile.h>
#include <vqm32/targa.h>
#include <vqm32/compress.h>
#include <vqm32/video.h>
#include <vqm32/palette.h>
#include <vqm32/vesavid.h>
#include <vqm32/vesablit.h>
#include <vqm32/graphics.h>
#include <vqm32/mixfile.h>
#include <vqm32/crc.h>
#include <vqm32/huffman.h>
#include <vqm32/mem.h>

#endif /* VQMALL_H */

