/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef WWLIB32_H
#define WWLIB32_H

#include <gbuffer.h>
#include <wwstd.h>
#include <drawbuff.h>
#include <buffer.h>
#include <font.h>
#include <iff.h>
#include <misc.h>
#include <mono.h>
#include <tile.h>
#include <wwmem.h>
#include <keyboard.h>
#include <mouse.h>
#include <file.h>
#include <rawfile.h>

#include <audio.h>
#include <dipthong.h>
#include <palette.h>
#include <playcd.h>
#include <shape.h>
#include <timer.h>
#include <ww_win.h>
#include <wsa.h>
#include <profile.h>



#endif // WWLIB32_H


