/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef WWTYPES_H
#define WWTYPES_H

#define	TRUE  1
#define	FALSE 0

#define	VOID    void
#define	PRIVATE static
#define	PUBLIC

#define	BOOL  short
#define	BYTE  char
#define	UBYTE unsigned char
#define	WORD  signed short
#define	UWORD unsigned short
#define	LONG  signed long
#define	ULONG unsigned long

#endif /* WWTYPES_H */

