/*
 * Copyright 2025 Electronic Arts Inc.
 *
 * Derived from Electronic Arts Inc.'s public source release for
 * Command & Conquer: Red Alert.
 * Licensed under GPLv3-or-later with additional Electronic Arts terms.
 * Modified for the macOS port, 2026.
 * See LICENSE.md.
 */

#ifndef WWLIB32_H
#define WWLIB32_H

#include <wwstd.h>

#include <audio.h>
#include <buffer.h>
#include <descmgmt.h>
#include	<dipthong.h>
#include <file.h>
#include <font.h>
#include <gbuffer.h>
#include <iff.h>
#include <keyboard.h>
#include <mcgaprim.h>
#include <misc.h>
#include <mono.h>
#include <palette.h>
#include <playcd.h>
#include <shape.h>
#include <tile.h>
#include <timer.h>
#include <video.h>
#include <vbuffer.h>
#include <window.h>
#include <wsa.h>
#include <wwmem.h>




#endif // WWLIB32_H

