get_filename_component(CNC95_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

include("${CNC95_REPO_ROOT}/cmake/cnc95_sources.cmake")

list(REMOVE_ITEM CNC95_SOURCES
    CODE/KEYFRAME.CPP
    CODE/CCDDE.CPP
    CODE/DDE.CPP
    CODE/TCPIP.CPP
    CODE/LZWOTRAW.CPP
    CODE/MPLIB.CPP
    CODE/MPLPC.CPP
    CODE/MPMGRD.CPP
    CODE/MPMGRW.CPP
    CODE/NETDLG.CPP
    CODE/NULLCONN.CPP
    CODE/NULLMGR.CPP
    CODE/TARCOM.CPP
    CODE/TEMP.CPP
)

set(CNC95_SUPPORT_SOURCES
    CODE/2KEYFRAM.CPP
    CODE/CRC.CPP
    CODE/FACE.CPP
    CODE/KEY.CPP
    CODE/MONOC.CPP
    CODE/NOSEQCON.CPP
    CODE/RAWFILE.CPP
    CODE/TARCOM.CPP
    CODE/WRITEPCX.CPP
    WIN32LIB/DRAWBUFF/BUFFER.CPP
    WIN32LIB/DRAWBUFF/BUFFGLBL.CPP
    WIN32LIB/DRAWBUFF/DRAWRECT.CPP
    WIN32LIB/DRAWBUFF/GBUFFER.CPP
    WIN32LIB/DRAWBUFF/ICONCACH.CPP
    WIN32LIB/DRAWBUFF/REGIONSZ.CPP
    WIN32LIB/FONT/FONT.CPP
    WIN32LIB/FONT/LOADFONT.CPP
    WIN32LIB/FONT/SET_FONT.CPP
    WIN32LIB/IFF/IFF.CPP
    WIN32LIB/IFF/LOAD.CPP
    WIN32LIB/KEYBOARD/MOUSE.CPP
    WIN32LIB/MEM/ALLOC.CPP
    WIN32LIB/MEM/MEM.CPP
    WIN32LIB/MISC/DDRAW.CPP
    WIN32LIB/MISC/DELAY.CPP
    WIN32LIB/MISC/EXIT.CPP
    WIN32LIB/MISC/FINDARGV.CPP
    WIN32LIB/MISC/IRANDOM.CPP
    WIN32LIB/MISC/LIB.CPP
    WIN32LIB/MISC/VERSION.CPP
    WIN32LIB/PLAYCD/GETCD.CPP
    WIN32LIB/PALETTE/PALETTE.CPP
    WIN32LIB/SHAPE/GETSHAPE.CPP
    WIN32LIB/SHAPE/PRIOINIT.CPP
    WIN32LIB/TILE/ICONSET.CPP
    WIN32LIB/TIMER/TIMER.CPP
    WIN32LIB/TIMER/TIMERDWN.CPP
    WIN32LIB/WSA/WSA.CPP
)

list(TRANSFORM CNC95_SOURCES PREPEND "${CNC95_REPO_ROOT}/")
list(TRANSFORM CNC95_SUPPORT_SOURCES PREPEND "${CNC95_REPO_ROOT}/")

set(CNC95_PLATFORM_SDL_SOURCES
    "${CNC95_REPO_ROOT}/PORT/MAC/src/mac_audio_stub.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/mac_sdl_runtime.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/mac_timer.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/mac_vqa.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/dos_compat.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/ccdde_stub.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/tcpip_stub.cpp"
    "${CNC95_REPO_ROOT}/PORT/MAC/src/legacy_primitives.cpp"
)

set(CNC95_INCLUDE_DIRS
    "${CNC95_REPO_ROOT}/PORT/MAC/include"
    "${CNC95_REPO_ROOT}/WIN32LIB/INCLUDE"
    "${CNC95_REPO_ROOT}/WIN32LIB/DRAWBUFF"
    "${CNC95_REPO_ROOT}/WIN32LIB/AUDIO"
    "${CNC95_REPO_ROOT}/WIN32LIB/FONT"
    "${CNC95_REPO_ROOT}/WIN32LIB/IFF"
    "${CNC95_REPO_ROOT}/WIN32LIB/MISC"
    "${CNC95_REPO_ROOT}/WIN32LIB/KEYBOARD"
    "${CNC95_REPO_ROOT}/WIN32LIB/MEM"
    "${CNC95_REPO_ROOT}/WIN32LIB/MONO"
    "${CNC95_REPO_ROOT}/WIN32LIB/PALETTE"
    "${CNC95_REPO_ROOT}/WIN32LIB/PLAYCD"
    "${CNC95_REPO_ROOT}/WIN32LIB/RAWFILE"
    "${CNC95_REPO_ROOT}/WIN32LIB/SHAPE"
    "${CNC95_REPO_ROOT}/WIN32LIB/TILE"
    "${CNC95_REPO_ROOT}/WIN32LIB/TIMER"
    "${CNC95_REPO_ROOT}/WIN32LIB/WSA"
    "${CNC95_REPO_ROOT}/CODE"
    "${CNC95_REPO_ROOT}/CODE/ENG"
    "${CNC95_REPO_ROOT}/CODE/WOLAPI"
    "${CNC95_REPO_ROOT}/WWFLAT32/INCLUDE"
    "${CNC95_REPO_ROOT}/WWFLAT32/MCGAPRIM"
    "${CNC95_REPO_ROOT}/WWFLAT32/AUDIO"
    "${CNC95_REPO_ROOT}/WWFLAT32/FILE"
    "${CNC95_REPO_ROOT}/WWFLAT32/FONT"
    "${CNC95_REPO_ROOT}/WWFLAT32/IFF"
    "${CNC95_REPO_ROOT}/WWFLAT32/MISC"
    "${CNC95_REPO_ROOT}/WWFLAT32/PALETTE"
    "${CNC95_REPO_ROOT}/WWFLAT32/SHAPE"
    "${CNC95_REPO_ROOT}/WWFLAT32/TILE"
    "${CNC95_REPO_ROOT}/WWFLAT32/TIMER"
    "${CNC95_REPO_ROOT}/WWFLAT32/VIDEO"
    "${CNC95_REPO_ROOT}/WWFLAT32/WINDOWS"
    "${CNC95_REPO_ROOT}/WWFLAT32/WSA"
    "${CNC95_REPO_ROOT}/WINVQ/INCLUDE"
    "${CNC95_REPO_ROOT}/WINVQ/INCLUDE/WWLIB32"
    "${CNC95_REPO_ROOT}/WINVQ/INCLUDE/VQM32"
    "${CNC95_REPO_ROOT}/VQ/INCLUDE"
    "${CNC95_REPO_ROOT}/VQ/INCLUDE/WWLIB32"
    "${CNC95_REPO_ROOT}/VQ/INCLUDE/VQM32"
)

set(CNC95_COMPILE_DEFINITIONS
    TRUE_FALSE_DEFINED
    WIN32
    _WINDOWS
    ENGLISH
    INTERNET_OFF
    GAME_VERSION=0x00030003
    VQADIRECT_SOUND=1
)

set(CNC95_COMPILE_OPTIONS
    -Wno-unknown-pragmas
    -Wno-deprecated-register
    -Wno-writable-strings
    -Wno-multichar
    -Wno-nonportable-include-path
    -Wno-deprecated-declarations
    -Wno-invalid-source-encoding
)

function(cnc95_configure_target target_name)
    target_include_directories(${target_name} PRIVATE ${CNC95_INCLUDE_DIRS})
    target_compile_definitions(${target_name} PRIVATE ${CNC95_COMPILE_DEFINITIONS})
    target_compile_options(${target_name} PRIVATE ${CNC95_COMPILE_OPTIONS})
endfunction()
